Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home_view),
    path('article/',include('article.urls'))
]

Blog/article/urls.py
from django.urls import path
from . import views
app_name="produit" 
urlpatterns = [
    path('' ,views.articles_view,name='articles'),
    path('cree/',views.cree_view,name='cree'),
    path('<slug:slug>/' ,views.article_view,name='article')
]

Blog/article/models.py
from django.db import models
class Article(models.Model):
    vorname=models.CharField(max_length=150)
    nachname=models.CharField(max_length=150)
    date_of_Birth=models.CharField(max_length=150)
    date_of_creation=models.DateTimeField(auto_now_add=True)
    slug=models.CharField(max_length=150)
    
    def __str__(self):
        return self.vorname
    

Blog/article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class meta:
        model=Article
        fields=['vorname','nachname','date_of_Birth','slug']

Blog/Blog/views.py
from django.http import HttpResponse
from django.shortcuts import  render
def Home_view(request):
    #return HttpResponse('je repond a une  requete')
    return render(request,'Home.html')

Blog/article/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import ArticleForm
from .models import Article
from django.http import Http404
from django.shortcuts import get_object_or_404

def articles_view(request):
    articles=Article.objects.all().order_by('date_of_creation')
    return render(request,'articles/article.html',context={'articles':articles})
   
def article_view(request,slug):
    article=get_object_or_404(Article,slug=slug)
    return render(request,'articles/list.html',context={'articles':article})
    #try:
     #   article=Article.objects.get(slug=slug)
     #   return render(request,'articles/detail.html',context={'article':article})
    #except Article.doesNotexist:
     #   raise Http404("page nexiste pas")
def cree_view(request):
    form = ArticleForm()
    return render(request,'articles/cree.html',context={'form':form})

Blog/article/templates/articles/article.html
{%extends 'extension.html'%}

{%block titre%} page_darticle{%endblock titre%}
{%block contenu%}
<h1>Ma page darticle</h1>
<a class="btn btn-primary" href="{% url 'produit:creet'%}">creet</a>
     {%for article in articles%}
         <h1><a href="{% url 'produit:article' slug=article.slug%}">{{article.nachname}}</a></h1>
         <h1><a href="">{{article.vorname}}</a></h1>
         <p>{{article.Birthdate}}</p>
        {%endfor %}

{%endblock contenu%}

Blog/article/templates/articles/cree.html
{%extends 'extension.html'%}
{%block contenu%}
     <form >
        {{form}}
     </form>
{%endblock contenu%}

Blog/article/templates/articles/creet.html
{%extends 'extension.html'%}
{%block contenu%}
     <form >
        {{form}}
     </form>
{%endblock contenu%}

Blog/article/templates/articles/detail.html
{%extends 'extension.html'%}
{%block contenu%}
     <h1>{{article.nachname}}</h1>
     <h1>{{article.vorname}}</h1>
     <p>{{article.Birthdate}}</p>
{%endblock contenu%}

Blog/templates/Home.html
{%extends 'extension.html'%}
{%block titre%}page_dacceuille{%endblock titre%}
{%block contenu%}<h1>Ma page dacceuille</h1>{%endblock contenu%}

Blog/templates/extension.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block titre%}{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>
<body>
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="{%url 'produit:articles'%}">article</a></li>
    </ul>

    {%block contenu%}

    {%endblock%}
    
</body>
</html>